vscode:
  extensions:
    - mitaki28.vscode-clang@0.2.3:a5z3DnVxXl8LmAXswnYRtg==
    - notskm.clang-tidy@0.5.1:+QMYmPGGWj0QCN6sba42Vw==
    - eclipse-cdt.cdt-gdb-vscode@0.0.91:IWeiNvZ9OnEVxNMv1giA+A==
    - weakish.complete-statement@0.4.0:NZQPhfLkbREikexlXZaQpQ==